---
- hosts: locanon
  user: vagrant
  vars:
    username: vagrant
    golang_version: 1.3.1
  tasks:
    - name: check tig installed
      command: rpm -q tig
      sudo: yes
      register: tig_installed
      failed_when: tig_installed.rc not in [0, 1]
    - name: install rpm package for tig
      command: rpm -i http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.2-2.el6.rf.x86_64.rpm
      sudo: yes
      when: tig_installed|failed
      register: tigrpm_install
      failed_when: tigrpm_install.rc not in [0, 1]
    - name: install yum packages
      yum: name={{item}} state=present
      with_items:
        - libselinux-python
        - git
        - git-core
        - zsh
        - vim
        - tig
        - tmux
      sudo: yes
    - name: change default shell
      user: name={{username}} shell=/bin/zsh
      sudo: yes
    - name: install oh-my-zsh
      git: repo=git://github.com/robbyrussell/oh-my-zsh dest=~/.oh-my-zsh
      notify: copy .zshrc and add hostname to prompt
    - name: make git template directory
      file: path=~/.git_template/hooks state=directory recurse=yes
    - name: copy dot files
      copy: src=files/dotfiles/{{item}} dest=~/{{item}}
      with_items:
        - .gitconfig
        - .gitignore_global
        - .git_template/hooks/pre-push
        - .vimrc
    - name: make vimrc dir
      file: path=~/.vim/rc state=directory mode=0755
    - name: copy vimrc files
      copy: src=files/dotfiles/.vim/rc/{{item}} dest=~/.vim/rc/{{item}}
      with_items:
        - .vimrc.basic
        - .vimrc.golang
        - .vimrc.plugins
    - name: copy bin files
      copy: src=files/bin/{{item}} dest=/usr/bin/{{item}} mode=0755
      with_items:
        - git_diff_wrapper
      sudo: yes
    - name: change git hook script mode
      file: path=~/.git_template/hooks/pre-push mode=0755
    - name: make NeoBundle dir
      file: path=~/.vim/bundle state=directory mode=0755
      notify: install NeoBundle
    - name: download Golang
      get_url: url=https://storage.googleapis.com/golang/go{{golang_version}}.linux-amd64.tar.gz dest=/tmp/go{{golang_version}}.tar.gz
      notify: install Golang

  handlers:
    - name: copy .zshrc and add hostname to prompt
      shell: cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc; echo 'export PROMPT="%{$fg_bold[blue]%}[{{inventory_hostname}}] $PROMPT"' >> ~/.zshrc
    - name: install NeoBundle
      git: repo=git://github.com/Shougo/neobundle.vim dest=~/.vim/bundle/neobundle.vim
    - name: install Golang
      shell: tar zxf /tmp/go{{golang_version}}.tar.gz -C ~; echo 'export GOROOT=~/go' >> ~/.zshrc; echo 'export GOPATH=$GOROOT/packages' >> ~/.zshrc; echo 'export PATH=$PATH:$GOROOT/bin:$GOPATH/bin' >> ~/.zshrc
      notify: install peco
    - name: install peco
      shell: source ~/.zshrc; go get github.com/lestrrat/peco/cmd/peco/; cat /vagrant/files/dotfiles/.zshrc.peco >> ~/.zshrc;
