---
- hosts: locanon
  user: vagrant
  sudo: yes
  vars:
    username: vagrant
    groupname: vagrant
    homedir: /home/{{username}}
    ohmyzsh_install_script: /tmp/install.ohmyz.sh
  tasks:
    - name: check tig installed
      command: rpm -q tig
      register: tig_installed
      failed_when: tig_installed.rc not in [0, 1]
    - name: install rpm package for tig
      command: rpm -i http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.2-2.el6.rf.x86_64.rpm
      when: tig_installed|failed
    - name: install yum packages
      yum: name={{item}} state=present
      with_items:
        - libselinux-python
        - git
        - git-core
        - zsh
        - vim
        - tig
        - tmux
    - name: change default shell
      user: name={{username}} shell=/bin/zsh
    - name: download oh-my-zsh
      get_url: url="http://install.ohmyz.sh" dest={{ohmyzsh_install_script}} mode=0555
      notify: replace oh-my-zsh install script file
      sudo: no
    - name: copy dot files
      copy: src=./dotfiles/{{item}} dest={{homedir}}/{{item}}
      with_items:
        - .gitconfig
        - .gitignore_global
        - .vimrc
      sudo: no
    - name: change .vim dir owner
      file: path={{homedir}}/.vim owner={{username}} group={{groupname}} state=directory mode=0755
    - name: make NeoBundle dir
      file: path={{homedir}}/.vim/bundle state=directory mode=0755
      sudo: no
      notify: install NeoBundle

  handlers:
    - name: replace oh-my-zsh install script file
      command: sed -i -e 's/env\ zsh//' -e 's/\.\ \~\/\.zshrc//' {{ohmyzsh_install_script}}
      notify: install oh-my-zsh
    - name: install oh-my-zsh
      shell: sh {{ohmyzsh_install_script}}
      sudo: no
      notify: add hostname to prompt
    - name: add hostname to prompt
      shell: echo 'export PROMPT="%{$fg_bold[blue]%}[{{inventory_hostname}}] $PROMPT"' >> {{homedir}}/.zshrc
    - name: install NeoBundle
      git: repo=git://github.com/Shougo/neobundle.vim dest={{homedir}}/.vim/bundle/neobundle.vim
      sudo: no
