---
- hosts: locanon
  user: vagrant
  sudo: yes
  vars:
    username: vagrant
    homedir: /home/{{username}}
    ohmyzsh_install_script: /tmp/install.ohmyz.sh
  tasks:
    - name: check tig installed
      command: rpm -q tig
      register: tig_installed
      failed_when: tig_installed.rc not in [0, 1]
    - name: install rpm package for tig
      command: rpm -i http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.2-2.el6.rf.x86_64.rpm
      when: tig_installed|failed
    - name: install yum packages
      yum: name={{item}} state=present
      with_items:
        - libselinux-python
        - git
        - git-core
        - zsh
        - vim
        - tig
        - tmux
    - name: change default shell
      user: name={{username}} shell=/bin/zsh
    - name: download oh-my-zsh
      get_url: url="http://install.ohmyz.sh" dest={{ohmyzsh_install_script}} mode=0555
      notify: replace oh-my-zsh install script file
    - name: copy dot files
      copy: src=./dotfiles/{{item}} dest={{homedir}}/{{item}}
      with_items:
        - .gitconfig
        - .gitignore_global
        - .vimrc

  handlers:
    - name: replace oh-my-zsh install script file
      command: sed -i -e 's/env\ zsh//' -e 's/\.\ \~\/\.zshrc//' {{ohmyzsh_install_script}}
      notify: install oh-my-zsh
    - name: install oh-my-zsh
      shell: sudo -su {{username}} {{ohmyzsh_install_script}}

